/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StudioImport } from './routes/studio'
import { Route as SimpleMidiTestImport } from './routes/simple-midi-test'
import { Route as RegisterImport } from './routes/register'
import { Route as MidiTestImport } from './routes/midi-test'
import { Route as MidiDirectTestImport } from './routes/midi-direct-test'
import { Route as LoginImport } from './routes/login'
import { Route as HomeImport } from './routes/home'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StudioRoute = StudioImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRoute,
} as any)

const SimpleMidiTestRoute = SimpleMidiTestImport.update({
  id: '/simple-midi-test',
  path: '/simple-midi-test',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const MidiTestRoute = MidiTestImport.update({
  id: '/midi-test',
  path: '/midi-test',
  getParentRoute: () => rootRoute,
} as any)

const MidiDirectTestRoute = MidiDirectTestImport.update({
  id: '/midi-direct-test',
  path: '/midi-direct-test',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/midi-direct-test': {
      id: '/midi-direct-test'
      path: '/midi-direct-test'
      fullPath: '/midi-direct-test'
      preLoaderRoute: typeof MidiDirectTestImport
      parentRoute: typeof rootRoute
    }
    '/midi-test': {
      id: '/midi-test'
      path: '/midi-test'
      fullPath: '/midi-test'
      preLoaderRoute: typeof MidiTestImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/simple-midi-test': {
      id: '/simple-midi-test'
      path: '/simple-midi-test'
      fullPath: '/simple-midi-test'
      preLoaderRoute: typeof SimpleMidiTestImport
      parentRoute: typeof rootRoute
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/midi-direct-test': typeof MidiDirectTestRoute
  '/midi-test': typeof MidiTestRoute
  '/register': typeof RegisterRoute
  '/simple-midi-test': typeof SimpleMidiTestRoute
  '/studio': typeof StudioRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/midi-direct-test': typeof MidiDirectTestRoute
  '/midi-test': typeof MidiTestRoute
  '/register': typeof RegisterRoute
  '/simple-midi-test': typeof SimpleMidiTestRoute
  '/studio': typeof StudioRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/midi-direct-test': typeof MidiDirectTestRoute
  '/midi-test': typeof MidiTestRoute
  '/register': typeof RegisterRoute
  '/simple-midi-test': typeof SimpleMidiTestRoute
  '/studio': typeof StudioRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/midi-direct-test'
    | '/midi-test'
    | '/register'
    | '/simple-midi-test'
    | '/studio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/midi-direct-test'
    | '/midi-test'
    | '/register'
    | '/simple-midi-test'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/midi-direct-test'
    | '/midi-test'
    | '/register'
    | '/simple-midi-test'
    | '/studio'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MidiDirectTestRoute: typeof MidiDirectTestRoute
  MidiTestRoute: typeof MidiTestRoute
  RegisterRoute: typeof RegisterRoute
  SimpleMidiTestRoute: typeof SimpleMidiTestRoute
  StudioRoute: typeof StudioRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MidiDirectTestRoute: MidiDirectTestRoute,
  MidiTestRoute: MidiTestRoute,
  RegisterRoute: RegisterRoute,
  SimpleMidiTestRoute: SimpleMidiTestRoute,
  StudioRoute: StudioRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/home",
        "/login",
        "/midi-direct-test",
        "/midi-test",
        "/register",
        "/simple-midi-test",
        "/studio"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/midi-direct-test": {
      "filePath": "midi-direct-test.tsx"
    },
    "/midi-test": {
      "filePath": "midi-test.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/simple-midi-test": {
      "filePath": "simple-midi-test.tsx"
    },
    "/studio": {
      "filePath": "studio.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
